### ISSUE TITLE
Optional DropDown treated as mandatory after 7.2.0 upgrade

### ISSUE THREAD

**Issue by c9mbundy** [umbraco/Umbraco.Forms.Issues#237]
An optional dropdown field that has an empty value selected, causes the submitted form to be silently discarded by the server, because it treats the optional field as mandatory.

This problem was introduced in 7.1.1 and fixed in 7.1.3 but is back again in 7.2.0

Compounding this issue is that Umbraco is not logging the fact that submitted forms are being discarded, and so it's only because it took me so long to find the problem in 7.1.1 and didn't trust the 7.2.0 upgrade that I was able to identify this issue. As mentioned in issue #224 the lack of trace-logging is a problem.

Reproduction
------------
Add an option dropdown field to a form, with no default value (because it's optional) and submit the forms with no value selected, and with value selected. If a value is selected then the submitted form is accepted and processed as expected, but if no value is selected, the form is silently discarded by the server, and the user is left thinking the form was successfully submitted while the server actually ignores it.

### Expected result
Optional should mean an empty value is valid.

### Actual result
Optional is treated as mandatory and submitted form is discarded.

---
_This item has been added to our backlog [AB#3199](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3199)_

**Comment by nul800sebastiaan** [comment]
Thanks @c9mbundy - we'll need to fix this for 7.2.1 - might also be relevant to 8.2.0, haven't investigated yet.

**Comment by DannerrQ** [comment]
I think I've hit this same problem but slightly different context. We've got a form with two dropdowns (Dropdown A and Dropdown B). Both dropdowns are mandatory, but Dropdown B has a condition to only show when Dropdown A is set to a specific value (e.g. 'Umbraco')

In this case I'd expect the form to submit successfully when Dropdown B is not displayed, with no value set for it. Instead the page does a post-back and you're left looking at the same form. Setting Dropdown A to 'Umbraco' at this point shows Dropdown B and a validation message - "Unexpected value: ''." Unless you do this there's no indication anything went wrong.

When Dropdown A is set to 'Umbraco' and Dropdown B is visible the form works as you'd expect and will submit successfully once a value is picked.

Is there any sort of timeline for getting 7.2.1 released? Would we be best reverting this update for now?

**Comment by snerpton** [comment]
> I think I've hit this same problem but slightly different context. We've got a form with two dropdowns (Dropdown A and Dropdown B). Both dropdowns are mandatory, but Dropdown B has a condition to only show when Dropdown A is set to a specific value (e.g. 'Umbraco')
> 
> In this case I'd expect the form to submit successfully when Dropdown B is not displayed, with no value set for it. Instead the page does a post-back and you're left looking at the same form. Setting Dropdown A to 'Umbraco' at this point shows Dropdown B and a validation message - "Unexpected value: ''." Unless you do this there's no indication anything went wrong.
> 
> When Dropdown A is set to 'Umbraco' and Dropdown B is visible the form works as you'd expect and will submit successfully once a value is picked.
> 
> Is there any sort of timeline for getting 7.2.1 released? Would we be best reverting this update for now?

Similar experience in a site (7.15.3) where I have just upgraded Umbraco Forms from 7.0.5 to 7.2.0. I've deleted the associated fields and recreated them, so I don't think the issue is upgrade related but rather a bug in 7.2.0.

@nul800sebastiaan Happy to help with any testing.

**Comment by bergmania** [comment]
Here is a version of Forms 7.2.0 with this issue hotfixed,

[UmbracoForms.Files.7.2.0-hotfix.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/3708782/UmbracoForms.Files.7.2.0-ci-20191009-002.zip)

**Comment by snerpton** [comment]
> Here is a version of Forms 7.2.0 with this issue hotfixed,
> 
> [UmbracoForms.Files.7.2.0-hotfix.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/3708782/UmbracoForms.Files.7.2.0-ci-20191009-002.zip)

Great work, I'll give this a test tomorrow. 

Am I correct in believing the fix is to append ` && model` to the `ng-if` attribute in `App_Plugins\UmbracoForms\Backoffice\Form\views\design\design.html`?

**Comment by bergmania** [comment]
@snerpton , no the fix for `App_Plugins\UmbracoForms\Backoffice\Form\views\design\design.html` is for another issue.

This issue is resolved in the dll, and can't be changed without the hotfix

**Comment by snerpton** [comment]
> @snerpton , no the fix for `App_Plugins\UmbracoForms\Backoffice\Form\views\design\design.html` is for another issue.
> 
> This issue is resolved in the dll, and can't be changed without the hotfix

Works for me, thanks @bergmania.

**Comment by JordinKee** [comment]
Since we're on Umbraco Cloud, I believe we cannot use the 7.2.0 hotfix mentioned here. When can we expect the 7.2.1 fix?

**Comment by tyradeveloper** [comment]
We are using Umbraco forms 7.2.0 and having a similar issue where we have a comma in a prevalue under multiple choice and the form stops to submit. the umbraco version is 7.15.3 and we are using cloud. I tried to use the hotfix but it didn't fix the issue.

**Comment by bergmania** [comment]
@JordinKee the hotfix can be used for Umbraco Cloud also.

**Comment by bergmania** [comment]
@tyradeveloper, The issue with the comma, is not really related to this issue, but is here: https://github.com/umbraco/Umbraco.Forms.Issues/issues/243

**Comment by JordinKee** [comment]
Thanks for the clarification, @bergmania! We will use this for the websites already upgraded to 7.2.0. Still, I would actually expect a new release (7.2.1) where this issue is fixed. Is that something we can expect in the (near) future?
