### ISSUE TITLE
Umbraco forms doesn't work under authentication against azure AD.

### ISSUE THREAD

**Issue by 3alexso** [umbraco/Umbraco.Forms.Issues#253]
Hi all, After debugging I  managed to understand that Umbraco forms don't work on the site using authentication against azure AD with user claims. 
When Umbraco forms added to pages located under azure AD login they call method StringHelper.ParsePlaceHolders in Umbraco.Forms.Data where seeing that the user is authenticated (context.User.Identity.IsAuthenticated) ask from the Umbraco's Membership system for the name of the member who logged in.
Umbraco returns Null (MembershipHelper.GetCurrentPersistedMember Method) because we do not use Umbraco members, and failing with an error.
Also looks like similar Member checks are in other places, for example in Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm
Please provide us with a fix or exact instructions on how can we make Umbraco Forms work after authentication with Azure AD.

---
_This item has been added to our backlog [AB#4154](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4154)_

**Comment by nul800sebastiaan** [comment]
Hi @3alexso. Just for your information, we don't have Azure AD support on our list of features at the moment so we don't expect it to work since we've never tested with it.

Can you please clarify: 
- The error you're getting
- The stack trace you're getting
- Are you using Azure AD for backoffice Users or frontend Members?

**Comment by nul800sebastiaan** [comment]
Oh and can you provide the configuration of your membership provider in web.config please?

**Comment by NickSafra** [comment]
Hi, I am Nick, a developer working in the project.
We are using Azure AD authentication for the front end. In the web.config we have the standard UmbracoMembershipProvider but we don't use it, there are no members in the Member section. Users authenticate against Azure AD and we work with User Claims. The problem is that pages with Umbraco Forms which work before the login to Azure AD stop working after the login. 
The error we get:

umbraco.macro - Error loading partial view macro (View: ~/Views/MacroPartials/InsertUmbracoFormWithTheme.cshtml). Exception: System.Web.HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Umbraco.Core.Cache.CacheProviderExtensions.GetCacheItem[T](ICacheProvider provider, String cacheKey, Func`1 getCacheItem)
   at Umbraco.Web.Security.MembershipHelper.GetCurrentPersistedMember() in d:\ewaveprojects\Umbraco-CMS-release-7.12.3\src\Umbraco.Web\Security\MembershipHelper.cs:line 794
   at Umbraco.Web.Security.MembershipHelper.GetCurrentMember() in d:\ewaveprojects\Umbraco-CMS-release-7.12.3\src\Umbraco.Web\Security\MembershipHelper.cs:line 375
   at Umbraco.Web.Security.MembershipHelper.GetCurrentMemberId() in d:\ewaveprojects\Umbraco-CMS-release-7.12.3\src\Umbraco.Web\Security\MembershipHelper.cs:line 389
   at Umbraco.Forms.Web.Controllers.UmbracoFormsController.GetFormModel(Guid formId, Nullable`1 recordId, String theme)
   at lambda_method(Closure , ControllerBase , Object[] )

**Comment by nul800sebastiaan** [comment]
Thanks Nick,

> The problem is that pages with Umbraco Forms which work before the login to Azure AD stop working after the login.

Can you elaborate? Sounds to me like backoffice users who are logged into Umbraco can not submit forms on the frontend?

**Comment by NickSafra** [comment]
No, this has no connection to backoffice and backoffice users at all.
These are external (internet) user who enter the front end and login via azure AD. After that when they enter a page containing Umbraco form (only enter, not submit!) the error is thrown, the form is not event seen in the page

**Comment by nul800sebastiaan** [comment]
> In the web.config we have the standard UmbracoMembershipProvider

Sure, but you must have a custom configuration for the `UsersMembershipProvider` then, no? 

From what I can read you are using Azure AD to authenticate users for the backoffice of Umbraco, right? 
If not, can you describe how you're using Azure AD together with Umbraco?

**Comment by nul800sebastiaan** [comment]
Alright, I think I get it. 

Since you haven't changed your `UmbracoMembershipProvider`, Forms is checking for logged in Members (your AAD members, which Umbraco knows nothing about). 

In order to fix this you might be able to remove the `UmbracoMembershipProvider` completely:

        <membership defaultProvider="UmbracoMembershipProvider" userIsOnlineTimeWindow="15">
            <providers>
                <clear />
                <add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco.Web" />
            </providers>
        </membership>

However, this might lead to other problems since Umbraco might be looking for that one.

Alternatively you could try and configure it as the `SqlMembershipProvider`, telling Umbraco and Forms we're not using the specific Umbraco version of the MembershipProvider, which will take code paths that should avoid the errors you're getting:

        <membership defaultProvider="UmbracoMembershipProvider" userIsOnlineTimeWindow="15">
            <providers>
                <clear />
                <add name="UmbracoMembershipProvider"
          type="System.Web.Security.SqlMembershipProvider"   
          connectionStringName="SqlServices"  
          applicationName="MyApplication"  
          enablePasswordRetrieval="false"  
          enablePasswordReset="true"  
          requiresQuestionAndAnswer="true"  
          requiresUniqueEmail="false"  
          passwordFormat="Hashed"  
          maxInvalidPasswordAttempts="5"  
          passwordAttemptWindow="10" />
                <add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco.Web" />
            </providers>
        </membership>

Does that help?

**Comment by NickSafra** [comment]
The second solution show the umbraco form in the page, indeed, we get rid of the error.
But on submit of the form we get another error:

[ArgumentNullException: Value cannot be null.
Parameter name: username]
   System.Web.Util.SecUtility.CheckParameter(String& param, Boolean checkForNull, Boolean checkIfEmpty, Boolean checkForCommas, Int32 maxSize, String paramName) +11726508
   System.Web.Security.Membership.GetUser(String username, Boolean userIsOnline) +57
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary`2 state, ControllerContext context) +742
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary`2 state) +91
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid) +490
   lambda_method(Closure , ControllerBase , Object[] ) +195

**Comment by nul800sebastiaan** [comment]
Right, the code involved here seems to not be doing proper checks.

The only immediate solution that might help is to switch to a custom "dummy" MembershipProvider that you build yourself. 

The failing code looks as follows currently:

```csharp
                if (System.Web.HttpContext.Current.User != null)
                {
                    //Do not need to check if this is an Umbraco Membership Provider as we are using the generic Security Membership in .NET Framework
                    if (System.Web.HttpContext.Current.User.Identity.IsAuthenticated && System.Web.Security.Membership.GetUser() != null)
                    {
                        record.MemberKey = System.Web.Security.Membership.GetUser().ProviderUserKey.ToString();
                    }
                }
```

So your custom membership provider needs to return a dummy member from GetUser() that has a non null ProviderUserKey.

I've sent this issue off to the Forms team to work on when they get a chance, I can not provide a timeline for a fix for this unfortunately.

**Comment by NickSafra** [comment]
The problem is that in this case you call System.Web.Security.Membership.GetUser - not the Umbraco DLL but the System DLL, and the dummy provider won't help here.
We really need a solution, as we use your module for a very important and big project.

**Comment by nul800sebastiaan** [comment]
It looks confusing but this is how providers work. System.Web.Security.Membership doesn't execute it's own code if a provider is registered.

**Comment by 3alexso** [comment]
Hi, I can see that the issue marked with estimation label,  is it means you are going to solve it? 
Do you have ETA? 
This Bug is really blocking us.

**Comment by nul800sebastiaan** [comment]
Yes, it is on our list to look in to. I don't have an ETA for you I'm afraid, we'll look at it in the next few sprints. For now, I recommend you attempt to implement the custom Membership Provider as mentioned before.

**Comment by mattikara** [comment]
Hi, 
Do you have any news regarding the issue?
Maybe now you can estimate when should we expect to get the fix?
Thanks,

**Comment by warrenbuckley** [comment]
@bergmania I have marked this for 8.3.0 unless we have a plan for a 8.2.1 that this will go in?

**Comment by 3alexso** [comment]
@warrenbuckley Is this fix will work either for Umbraco version 7.12.3 ?

**Comment by bergmania** [comment]
@warrenbuckley, I guess we could just bump all `8.2.1` to `8.3.0` and aim for `8.3.0` as next release

**Comment by warrenbuckley** [comment]
@bergmania This was cherry-picked into `dev/v7` branch as well with commit SHA 03ac52ef2eaa21927ab9c44d9b812a0df827c4fc

**Comment by mattikara** [comment]
@bergmania , Hi
where can we find the release for Umbraco 7? 
We can't find it in the git...

**Comment by bergmania** [comment]
@mattikara 7.3.0 is not released yet..

The plan is to release tomorrow.

**Comment by mattikara** [comment]
Thanks!

We will wait for it…

**Comment by NickSafra** [comment]
The issue is not resolved fully in 7.3.0.
We see the form after login to the Azure AD (it is fixed in the new version)
But after filling and submitting the form we get the following error:

ArgumentNullException: Value cannot be null.
Parameter name: username]
   System.Web.Util.SecUtility.CheckParameter(String& param, Boolean checkForNull, Boolean checkIfEmpty, Boolean checkForCommas, Int32 maxSize, String paramName) +11728268
   System.Web.Security.Membership.GetUser(String username, Boolean userIsOnline) +57
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.SubmitForm(Form form, FormViewModel model, Dictionary`2 state, ControllerContext context) +823
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.GoForward(Form form, FormViewModel model, Dictionary`2 state) +91
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.HandleForm(FormViewModel model, Boolean captchaIsValid) +490
   lambda_method(Closure , ControllerBase , Object[] ) +195
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +77
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +188
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +602
   System.Web.<>c__DisplayClass285_0.<ExecuteStepImpl>b__0() +35
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +143
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +128

Please fix the error, this is very urgent for or project, thanks.

**Comment by Djasp** [comment]
We are experiencing the same issue. Our users are authenticated against OpenAM, not AD, but otherwise the behaviour is similar. 

To circumvent the code in Umbraco Forms 7.1.3 (that supposedly was fixed in 7.3.0 but is not) we've added the following to `Views\MacroPartials\InsertUmbracoFormWithTheme.cshtml`:

````
    var current = HttpContext.Current;
    if (current?.User?.Identity != null && current.User.Identity.IsAuthenticated)
    {   //Authenticated user
        var currentUser = current.User; 
	    HttpContext.Current.User = null; //temporary empty user object
        Html.RenderAction("RenderForm", "UmbracoForms", new { formId = form, recordId = recordGuid, theme = theme, includeScripts = includeScripts });
        HttpContext.Current.User = currentUser; // reset user object
    }
````
This renders the form on the page, but after the submit we get the same error as @NickSafra `(ArgumentNullException: Value cannot be null.
Parameter name: username)`

My best guess it that upon receiving the POST-request there is some code that assumes `HttpContext.Current.User.Identity.GetUserName()` not returning an empty string.

**Comment by bergmania** [comment]
I wonder why this stack trace mentions we use 
```
System.Web.Security.Membership.GetUser(String username, Boolean userIsOnline) 
```
We use the overload without any parameters and our code seem pretty defensive:
```
var loggedInMember = System.Web.Security.Membership.GetUser();
if (loggedInMember != null)
    record.MemberKey = loggedInMember.ProviderUserKey != null ? loggedInMember.ProviderUserKey.ToString() : null;
```

I seem to a problem the way `System.Web.Security.Membership.GetUser()` get the username. 

```
    public static MembershipUser GetUser()
    {
      return Membership.GetUser(Membership.GetCurrentUserName(), true);
    }

    private static string GetCurrentUserName()
    {
      if (HostingEnvironment.IsHosted)
      {
        HttpContext current = HttpContext.Current;
        if (current != null)
          return current.User.Identity.Name;
      }
      IPrincipal currentPrincipal = Thread.CurrentPrincipal;
      return currentPrincipal == null || currentPrincipal.Identity == null ? string.Empty : currentPrincipal.Identity.Name;
    }
```

So it seems to be the case that `current.User.Identity.Name == null`

I have tried to fix this by getting the username our self, and only if we can get a username call the `System.Web.Security.Membership.GetUser(username)`

Can one of you test this patch?

[UmbracoForms.Files.7.3.1-ci-20200205-001.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4159881/UmbracoForms.Files.7.3.1-ci-20200205-001.zip)

**Comment by Djasp** [comment]
@bergmania Thanks for the quick response! 

I've applied the patch 7.3.1 locally and was able to submit the form successfully when logged in via OpenAm. The patch overwrote our hack in `InsertUmbracoFormWithTheme` but the form rendered just fine without it.

**Comment by karlitros** [comment]
Hi,

I've installed the official 7.3.1 release of Umbraco Forms, (also had a go with your aforementioned patch), and am still getting the error with the stack trace. This occurs when the form is trying to render.

`[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem) +288
   Umbraco.Core.Cache.CacheProviderExtensions.GetCacheItem(ICacheProvider provider, String cacheKey, Func`1 getCacheItem) +115
   Umbraco.Web.Security.MembershipHelper.GetCurrentPersistedMember() +91
   Umbraco.Web.Security.MembershipHelper.GetCurrentMember() +31
   Umbraco.Web.Security.MembershipHelper.GetCurrentMemberId() +33
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.GetFormModel(Guid formId, Nullable`1 recordId, String theme) +135
   lambda_method(Closure , ControllerBase , Object[] ) +351`

Is this an additional issue, or something I've missed above in this thread?

**Comment by Djasp** [comment]
We've installed the official 7.3.1 release, and we have the same error message.

I don't know what circumstances caused my test with the patch to work, but I know think it was a false positive. 

We've for now resorted to prompt users to logout before showing the form :-(

I'd be more than willing to provide more assistance in debugging this issue.

**Comment by bergmania** [comment]
I have a hard time reproducing, but I tried to catch possible exceptions from `Umbraco.Web.Security.MembershipHelper.GetCurrentMemberId()`.

This will not solve the root cause, but maybe you can test if this works:

[UmbracoForms.Files.7.3.1-hotfix.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4229790/UmbracoForms.Files.7.3.1-ci-20200220-001.zip)

**Comment by mattikara** [comment]
For us, the fix is working fine. Thanks!

**Comment by bergmania** [comment]
@mattikara right now the hotfix logs an error. Can you post that log entry here? Thanks

**Comment by karlitros** [comment]
Hi,

Just to throw our 2p in as well, the hotfix hasn't changed anything our side. Our stack trace mentioned above is still the same.

Cheers,

Karl

**Comment by bergmania** [comment]
@karlitros, sounds weird.. There is a try-catch(exception) around the method call from that stack trace

```
Umbraco.Forms.Web.Controllers.UmbracoFormsController.GetFormModel(Guid formId, Nullable1 recordId, String theme) +135
```

**Comment by karlitros** [comment]
Weird indeed! Hopefully to shed some light, here's the full stack trace:

`Server Error in '/' Application.
Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error:


Line 10:     <section class="page__row page__row--center  page__row--add-padding-left-right">
Line 11:         @{
Line 12:             Html.RenderAction("RenderForm", "UmbracoForms", new { formId = Model.Content.GetPropertyValue<string>("formPicker"), includeScripts = true });
Line 13:         }
Line 14:     </section>

Source File: C:\development\rtpi-site\RTPI.Website\Views\FormPage.cshtml    Line: 12

Stack Trace:


[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem) +288
   Umbraco.Core.Cache.CacheProviderExtensions.GetCacheItem(ICacheProvider provider, String cacheKey, Func`1 getCacheItem) +115
   Umbraco.Web.Security.MembershipHelper.GetCurrentPersistedMember() +91
   Umbraco.Web.Security.MembershipHelper.GetCurrentMember() +31
   Umbraco.Web.Security.MembershipHelper.GetCurrentMemberId() +33
   Umbraco.Forms.Web.Controllers.UmbracoFormsController.GetFormModel(Guid formId, Nullable`1 recordId, String theme) +140
   lambda_method(Closure , ControllerBase , Object[] ) +351
   System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +14
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +157
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27
   System.Web.Mvc.Async.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +22
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0() +58
   System.Web.Mvc.Async.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228
   System.Web.Mvc.Async.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228
   System.Web.Mvc.Async.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228
   System.Web.Mvc.Async.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228
   System.Web.Mvc.Async.<>c__DisplayClass7_0.<BeginInvokeActionMethodWithFilters>b__1(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__4() +35
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45
   System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.Mvc.<>c__DisplayClass3_0.<EndProcessRequest>b__0() +22
   System.Web.Mvc.<>c__DisplayClass5_0.<Wrap>b__0() +10
   System.Web.Mvc.ServerExecuteHttpHandlerWrapper.Wrap(Func`1 func) +27
   System.Web.Mvc.ServerExecuteHttpHandlerWrapper.Wrap(Action action) +64
   System.Web.Mvc.ServerExecuteHttpHandlerAsyncWrapper.EndProcessRequest(IAsyncResult result) +71
   System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride) +1498

[HttpException (0x80004005): Error executing child request for handler 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.]
   System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride) +3565137
   System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage) +80
   System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm) +30
   System.Web.HttpServerUtilityWrapper.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm) +25
   System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter) +468
   System.Web.Mvc.Html.ChildActionExtensions.RenderAction(HtmlHelper htmlHelper, String actionName, String controllerName, Object routeValues) +43
   ASP._Page_Views_FormPage_cshtml.<Execute>b__3_0() in C:\development\rtpi-site\RTPI.Website\Views\FormPage.cshtml:12
   System.Web.WebPages.<>c__DisplayClass42_0.<RenderSection>b__0(TextWriter tw) +316
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +80
   ASP._Page_Views_Global_cshtml.Execute() in C:\development\rtpi-site\RTPI.Website\Views\Global.cshtml:23
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +198
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +105
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +90
   System.Web.WebPages.<>c__DisplayClass40_0.<RenderPageCore>b__0(TextWriter writer) +232
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +80
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +63
   System.Web.WebPages.WebPageBase.PopContext() +237
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +98
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +235
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +107
   Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer) +113
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +290
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__4() +198
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45
   System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9836613
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +50
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4075.0`

**Comment by bergmania** [comment]
`GetCurrentMemberId` is only called once in `UmbracoFormsController`. 

In the hotfix with the following code:
```
[...]
                    try
                    {
                        memid = Members.GetCurrentMemberId();
                    }
                    catch (Exception e)
                    {
                        Logger.Error(typeof(UmbracoFormsController), "Can't get the current members Id", e);
                    }
```

@karlitros, are you sure the dll is updated to the hotfix?

**Comment by karlitros** [comment]
Thanks very much, you pointed out that the hot-fix in the bin directory was being overwritten with the old package contents every time I ran the site! Doh! I ran the site in IIS and copied the bin files over again, and now get the following stack trace:

https://www.codepile.net/pile/WNO3V4N0

**Comment by bergmania** [comment]
Thanks.. This error is related to the original issue. But on a completely other end of the system.

I have tried to build a new hotfix:
[UmbracoForms.Files.7.3.1-ci-20200220-002.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4231303/UmbracoForms.Files.7.3.1-ci-20200220-002.zip)

**Comment by karlitros** [comment]
Ah ha! Yep that's sorted it! Well done!

What's the best plan going forward in terms of making this a bit more permanent?

Thanks very much for your help on getting this through, you're a legend!

**Comment by sbesteman** [comment]
Does someone have a temp fix for 8.3.1? Thanks in advance

**Comment by bergmania** [comment]
Hi @sbesteman 
Take a look here: https://github.com/umbraco/Umbraco.Forms.Issues/issues/253#issuecomment-589086020

I would like more people to test the hotfix, because I can't reproduce in my dev environment.

**Comment by bergmania** [comment]
Hi @sbesteman 

Please try this hotfix and return with feedback. The more test the better, because I can't reproduce in by dev environment.

[UmbracoForms.Files.8.3.1-alpha.221.zip](https://github.com/umbraco/Umbraco.Forms.Issues/files/4243507/UmbracoForms.Files.8.3.1-alpha.221.zip)

**Comment by sbesteman** [comment]
Hi @bergmania,

Thanks for the hotfix. It brought me to the fix. But the fix was not in the hotfix. A page with Umbraco forms under azure ad IdConnectAuthentication needs the following Owin settings

The bold items below are importent to get it to work

{
app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                    // Sets the ClientId, authority, RedirectUri as obtained from web.config
                    ClientId = ClientId,
                    Authority = Authority,
                    RedirectUri = RedirectUri,

                    // PostLogoutRedirectUri is the page that users will be redirected to after sign-out. In this case, it is using the home page
                    PostLogoutRedirectUri = RedirectUri,
                    Scope = $"{OpenIdConnectScope.OpenIdProfile} {OpenIdConnectScope.OfflineAccess}",
                    // ResponseType is set to request the id_token - which contains basic information about the signed-in user
                    ResponseType = OpenIdConnectResponseType.IdToken,
                    // ValidateIssuer set to false to allow personal and work accounts from any organization to sign in to your application
                    // To only allow users from a single organizations, set ValidateIssuer to true and 'tenant' setting in web.config to the tenant name
                    // To allow users from only a list of specific organizations, set ValidateIssuer to true and use ValidIssuers parameter 
                    TokenValidationParameters = new TokenValidationParameters()
                    {
                        ValidateIssuer = true,
                        **NameClaimType = ClaimTypes.NameIdentifier**
                    },
                    // OpenIdConnectAuthenticationNotifications configures OWIN to send notification of failed authentications to OnAuthenticationFailed method
                    Notifications = new OpenIdConnectAuthenticationNotifications
                    {
                        AuthenticationFailed = OnAuthenticationFailed
                    },

                    AuthenticationType = string.Format(
                        CultureInfo.InvariantCulture,
                        "https://sts.windows.net/{0}/{1}]",
                        Tenant, "Front"),
                }
            );

            **AntiForgeryConfig.UniqueClaimTypeIdentifier = ClaimTypes.NameIdentifier;**
}
