### ISSUE TITLE
Umbraco Forms: 8.7.3 ReCaptcha v3 results in You have failed Google ReCaptcha V3 

### ISSUE THREAD

**Issue by Jancornillie** [umbraco/Umbraco.Forms.Issues#571]
When using a ReCaptcha V3 with Umbraco Forms: 8.7.3, no matter what I do, I always get message "You have failed Google ReCaptcha V3"

When trying to submit a form with this Recaptcha V3 (treshhold 0.5) I find in my Log viewer the following warning:

{
	"@t": "2021-05-19T14:16:11.4969491Z",
	"@mt": "The Google reCAPTCHA score {RecaptchaScore} did not meet the user definied threshold of {FieldThreshold} for the field {FieldAlias} on {FormName}",
	"@l": "Warning",
	**"RecaptchaScore": 0.9,
	"FieldThreshold": 5,**
	"FieldAlias": "rc3",
	"FormName": "Contact form",
	"SourceContext": "Umbraco.Forms.Core.Providers.FieldTypes.Recaptcha3",
	"ProcessId": 22764,
	"ProcessName": "w3wp",
	"ThreadId": 97,
	"AppDomainId": 2,
	"AppDomainAppId": "LMW3SVC205ROOT",
	"MachineName": "WEB18",
	"Log4NetLevel": "WARN ",
	"HttpSessionId": "qwrnp3kvxqrvsm4ggrahecik",
	"HttpRequestNumber": 22,
	"HttpRequestId": "04f031bc-74ef-474c-b9fb-befd3bf12f12"
}

Where I suspect the **FieldThreshold** should have been 0.5 instead of 5.

Might there be a localization issue here? (I have a Dutch language site, in French it is the same)

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Actual result

---
_This item has been added to our backlog [AB#12022](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12022)_

**Comment by AndyButland** [comment]
Hi - yes, it does look like a localisation issue.  I've done a quick test using "0,5" as the score, and with our logic we are parsing that as 5.  Just to confirm the issue, would you be able to check please if [this update](https://drive.google.com/file/d/1h1dRtsg-JRO9mvpMfQmJ27RWa_K-RHDp/view?usp=sharing) resolves it?

Inside the zip is a single dll that you can copy into your bin folder in a development environment, replacing the one that's already there (which you should back-up first).

Thanks for confirming if you can, and if so, we'll get this fixed in an upcoming patch release.

**Comment by rickread** [comment]
That's amazing guys, I only encountered this issue today and found someone had beat me to the punch. I'll test out the patch too.

Thanks
Rick

**Comment by Jancornillie** [comment]
@AndyButland 
Unfortunately the update did not solve this. Same log warning with FieldThreshold = 5 instead of 0.5. I removed field from form and added it again but still same result.

@rickread 
I'm so sorry, if I knew I would have waited :)

**Comment by AndyButland** [comment]
Hmm... OK, I'll do some more tests to see if we can resolve.

**Comment by rickread** [comment]
@AndyButland if it helps, I think the issue is occurring in the following code of Recaptcha3.ValidateField:  `double.TryParse(this.ScoreThreshold, out result) `

Apologies - I was trying to understand the issue myself so peeked at the source. I don't know if the update tried applying an invariant culture, so the ScoreThreshold value gets parsed in the same way?

**Comment by AndyButland** [comment]
Thanks @rickread, looks like it yes.  No need to apologies, I appreciate the help!  I think I had to handle replacing a `,` with a `.` too, and that hopefully this will have solved it.  Seems OK in my tests but again if either of you are able to give [this](https://drive.google.com/file/d/1kyTK4Thd33MwNdwq1zw_t7E7Crb-mSx6/view?usp=sharing) a quick check in your environment please that would be great.

**Comment by Jancornillie** [comment]
@AndyButland 
No, not working, this does throw an exception:
Method not found: 'Boolean Umbraco.Forms.Core.Extensions.StringExtensions.TryParseToDouble(System.String, Double ByRef)'.

**Comment by Jancornillie** [comment]
Hello @AndyButland 
This time it works as expected, did this on 2 different sites, so seems solved like this
Thanks!

**Comment by AndyButland** [comment]
That's good to hear, thanks.  We'll get this out with the next patch release.

**Comment by ronaldbarendse** [comment]
In addition to correctly parsing the threshold score, it will become possible to set the threshold to 0 and have all submissions pass (e.g. when you want to temporarily disable the reCAPTCHA check without removing the field) 🎉 

The returned score is currently not saved on the entry though. This might make sense if you want to accept all submissions and manually approve them: having the score available will give some additional context about how 'spammy' it is according to reCAPTCHA. Please create a new feature request if you'd like this functionality added, so we know if it's a valid use-case 😄
